/*
 * bsp.c
 *
 *  Created on: Mar 31, 2021
 *      Author: pwiklowski
 */


/**@brief Function for the Timer initialization.
 *
 * @details Initializes the timer module. This creates and starts application timers.
 */
static void timers_init(void)
{
  ret_code_t err_code = app_timer_init();
  APP_ERROR_CHECK(err_code);
}


/**@brief Function for initializing buttons and leds.
 *
 * @param[out] p_erase_bonds  Will be true if the clear bonding button was pressed to wake the application up.
 */
static void buttons_leds_init(bool *p_erase_bonds)
{
  ret_code_t err_code;
  bsp_event_t startup_event;

  err_code = bsp_init(BSP_INIT_LEDS | BSP_INIT_BUTTONS, bsp_event_handler);
  APP_ERROR_CHECK(err_code);

  err_code = bsp_btn_ble_init(NULL, &startup_event);
  APP_ERROR_CHECK(err_code);

  *p_erase_bonds = (startup_event == BSP_EVENT_CLEAR_BONDING_DATA);
}


/**@brief Function for putting the chip into sleep mode.
 *
 * @note This function will not return.
 */
//static void sleep_mode_enter(void) {
//  ret_code_t err_code;
//
//  err_code = bsp_indication_set(BSP_INDICATE_IDLE);
//  APP_ERROR_CHECK(err_code);
//
//  // Prepare wakeup buttons.
//  err_code = bsp_btn_ble_sleep_mode_prepare();
//  APP_ERROR_CHECK(err_code);
//
//  // Go to system-off mode (this function will not return; wakeup will cause a reset).
//  //err_code = sd_power_system_off();
//  //APP_ERROR_CHECK(err_code);
//}



/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
static void bsp_event_handler(bsp_event_t event) {
//  ret_code_t err_code;
//
//  switch (event)
//  {
//  case BSP_EVENT_SLEEP:
//    sleep_mode_enter();
//    break;
//
//  case BSP_EVENT_DISCONNECT:
//    err_code = sd_ble_gap_disconnect(m_conn_handle, BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
//    if (err_code != NRF_ERROR_INVALID_STATE) {
//      APP_ERROR_CHECK(err_code);
//    }
//    break;
//
//  case BSP_EVENT_WHITELIST_OFF:
//    if (m_conn_handle == BLE_CONN_HANDLE_INVALID) {
//      err_code = ble_advertising_restart_without_whitelist(&m_advertising);
//      if (err_code != NRF_ERROR_INVALID_STATE) {
//        APP_ERROR_CHECK(err_code);
//      }
//    }
//    break;
//
//  default:
//    break;
//  }
}
